# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 158)
        Dialog.setModal(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 191, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.easyLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.easyLabel.setStyleSheet("font-weight: bold;")
        self.easyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.easyLabel.setObjectName("easyLabel")
        self.verticalLayout_4.addWidget(self.easyLabel)
        self.mediumLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mediumLabel.setStyleSheet("font-weight: bold;")
        self.mediumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mediumLabel.setObjectName("mediumLabel")
        self.verticalLayout_4.addWidget(self.mediumLabel)
        self.proLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.proLabel.setStyleSheet("font-weight: bold;")
        self.proLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.proLabel.setObjectName("proLabel")
        self.verticalLayout_4.addWidget(self.proLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Лучшие результаты"))
        self.label_2.setText(_translate("Dialog", "Новичок"))
        self.label_4.setText(_translate("Dialog", "Любитель"))
        self.label_3.setText(_translate("Dialog", "Профессионал"))
        self.easyLabel.setText(_translate("Dialog", "999"))
        self.mediumLabel.setText(_translate("Dialog", "999"))
        self.proLabel.setText(_translate("Dialog", "999"))
